Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "water")
Ingredient.create(name: "matcha")
Ingredient.create(name: "weed")

Cocktail.create(name: "Blue")
Cocktail.create(name: "Marly")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Pina")
Cocktail.create(name: "Virgin")
Cocktail.create(name: "Menthe")
